
- hosts: worker1
  become: true
  gather_facts: no
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Start Docker Service
      service:
        name: docker
        state: started
